### ISSUE TITLE
How to invoke an easyargs class in unittesting

### ISSUE THREAD

**Issue by innovia** [stedmeister/easyargs#12]
HI

I can't figure out how to unit test a class with @easyargs.

can you please provide directions?

when I attempt to call my class it thinks that pytest is the main script.
```python
  s = Myclass()
```
usage: pytest [-h] {cleanup,logs,run,status,sync} ...

**Comment by stedmeister** [comment]
Hi innovia

That is a good question.  I found the best way to do this is to split out the function that does the work from the main easyargs class.  Then the options can be changed by patching sys.argv.  This is probably best demonstrated by some code:

    import mock
    import unittest

    # Here is where the actual work is done
    def actual_work_function(foo, bar=1):
        print ('actual_work_function', foo, bar)


    # This is the parser class
    @easyargs
    class ArgParser(object):
        def do_work(self, foo, bar=1):
            actual_work_function(foo, bar)


    # Unit test class
    # You'll need to change where items are patched
    class TestIntegration(unittest.TestCase):
        @mock.patch('__main__.actual_work_function', autospec=True)  # Mock work function
        def test_bar_is_parsed(self, work_function):
            # Patch sys.argv with the actual arguments
            with mock.patch('sys.argv', [__name__, 'do_work', 'hello', '--bar', '2']):
                # Test
                ArgParser()

                # Assert
                work_function.assert_called_with('hello', 2)

    if __name__ == '__main__':
        unittest.main()

At the moment, I don't think that there is a better way of doing it.  I feel that I should at least allow the parsing of arguments rather than having to patch sys.argv.  Hope that helps.

**Comment by innovia** [comment]
funny that's what i ended up doing i am calling invoke_run(arg) on my easyargs class
and testing the invoke_run method instead.

but I see now how you are calling the ArgParser class.

Thanks
